name: Dripyard Great Lakes Canvas Patterns
type: Dripyard
description: 'Provides component patterns for Drupal Canvas using Great Lakes theme'
install:
  - canvas
config:
  strict: false
recipes:
  - 'dripyard_canvas_patterns'
