services:
  cli:
    image: docksal/cli:php8.3
  db:
    image: docksal/mariadb:10.6
    environment:
      - PANTHEON_SITE_ENV
  solr:
    hostname: solr
    image: docksal/solr:1.0-solr3
    ports:
      - "8987:8987"
    environment:
      - DOMAIN_NAME=solr.${VIRTUAL_HOST}
