#!/bin/sh

# Get all files attempting to be changed from HEAD.
files=`git diff --cached --name-only`

# Execute PHP Code Sniffer for Coding Standards.
fin exec phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css ${files}
if [ $? -ne 0 ]; then
 echo "Coding Standard errors were found in the files you are committing. Please make all listed adjustments and commit again."
 exit 1
fi

# Execute PHP Code Sniffer for Drupal Best Practices.
fin exec phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css ${files}
if [ $? -ne 0 ]; then
 echo "The code you are committing are violating Drupal's Best Practices. Please make all listed adjustments and commit again."
 exit 1
fi
