global:
  header: false
  css:
    theme:
      dist/style.css: {}
  js:
    components/04-assembly/global/site.js: {}
    components/02-chunks/navigation/main-navigation/main-navigation.js: {}
  dependencies:
    - core/drupal
    - core/drupal.debounce
    - core/drupalSettings
    - core/jquery
    - core/once
accordion:
  js:
    components/03-composites/paragraphs/accordions/accordions.js: {}
  dependencies:
    - core/drupal.debounce
forms:
  js:
    components/01-parts/forms/forms.js: {}
pager:
  js:
    components/02-chunks/pagers/pager.js: {}
search-block:
  js:
    components/03-composites/blocks/search/search-block.js: {}
on-page-menu:
  js:
    components/02-chunks/navigation/on-page-menu/on-page-menu.js: {}
  dependencies:
    - core/drupal.debounce
select:
  version: 4.1.0-rc.0
  css:
    theme:
      components-addons/select2/select2.min.css: { minified: true }
  js:
    components-addons/select2/select2.min.js: { minified: true }
    components/01-parts/forms/forms.js: {}
table:
  css:
    theme:
      components-addons/basictable/basictable.css: {}
  js:
    components/01-parts/tables/tables.js: {}
    components-addons/basictable/jquery.basictable.min.js: { minified: true }
views:
  js:
    components/03-composites/views/views.js: {}
