global:
  header: false
  css:
    theme:
      dist/style.css: {}
  js:
    components/04-assembly/global/site.js: {}
    components/02-chunks/navigation/main-navigation/main-navigation.js: {}
  dependencies:
    - core/drupal
    - core/drupal.debounce
    - core/drupalSettings
    - core/jquery
    - core/once
accordion:
  js:
    components/03-composites/paragraphs/accordions/accordions.js: {}
  dependencies:
    - core/drupal.debounce
alerts:
  js:
    components/03-composites/views/alerts/alerts.js: {}
drawers:
  js:
    components/02-chunks/drawers/drawers.js: {}
featherlight:
  version: 1.7.13
  css:
    theme:
      components-addons/featherlight/featherlight.css: {}
      components-addons/featherlight/featherlight.gallery.css: {}
  js:
    components-addons/featherlight/featherlight.min.js: { minified: true }
    components-addons/featherlight/featherlight.gallery.min.js: { minified: true }
fonts:
  css:
    theme:
      https://fonts.googleapis.com/css?family=Lato:ital,wght@0,300;;0,400;;0,700;;0,900;1,400: { type: external, preprocess: false }
forms:
  js:
    components/01-parts/forms/forms.js: {}
galleries:
  js:
    components/03-composites/paragraphs/gallery/gallery.js: {}
jump-links:
  version: 1.0
  js:
    components/03-composites/blocks/intro/intro.js: { }
modal:
  js:
    components/02-chunks/modals/modals.js: {}
pager:
  js:
    components/02-chunks/pagers/pager.js: {}
search-block:
  js:
    components/03-composites/blocks/search/search-block.js: {}
section-menu:
  js:
    components/02-chunks/navigation/section-menu/section-menu.js: {}
  dependencies:
    - core/drupal.debounce
select:
  version: 4.0.3
  css:
    theme:
      components-addons/select2/select2.min.css: { minified: true }
  js:
    components-addons/select2/select2.min.js: { minified: true }
    components/01-parts/forms/forms.js: {}
slick:
  version: 1.8.1
  css:
    theme:
      components-addons/slick/slick.css: {}
      components-addons/slick/slick-theme.css: {}
  js:
    components-addons/slick/slick.min.js: { minified: true }
table:
  css:
    theme:
      components-addons/basictable/basictable.css: {}
  js:
    components/01-parts/tables/tables.js: {}
    components-addons/basictable/jquery.basictable.min.js: { minified: true }
views:
  js:
    components/03-composites/views/views.js: {}
